### ISSUE TITLE
Forget user feature missing

### ISSUE THREAD

**Issue by Aky22** [mailerlite/mailerlite-nodejs#29]
According to the official MaierLite Api documentation, they provide an endpoint to remove the subscriber from your account and all information will be completly deleted after 30 days too. However this package doesn't implement this call.

Please implement this feature.

https://developers.mailerlite.com/docs/subscribers.html#forget-a-subscriber

**Comment by Mantas97** [comment]
Forget the user endpoint released in [v.1.1.0](https://github.com/mailerlite/mailerlite-nodejs/releases/tag/v.1.1.0)
