### ISSUE TITLE
subscribers.get() Does not return groups as documented

### ISSUE THREAD

**Issue by klcodanr** [mailerlite/mailerlite-nodejs#35]
The Docs for the NodeJS SDK indicate that the call to subscribers.get() should return the list of group id's on each subscriber:

https://github.com/mailerlite/mailerlite-nodejs/blob/main/src/modules/subscribers/subscribers.module.ts

However, the groups attribute is not contained in the returned subscriber object:

![image](https://github.com/mailerlite/mailerlite-nodejs/assets/2946250/60b37d3a-e802-4914-aab4-af693def4df5)

I think this may actually be an issue with the API which also indicates that subscribers should return a list of group id's but does not either:

https://developers.mailerlite.com/docs/subscribers.html#list-all-subscribers
![image](https://github.com/mailerlite/mailerlite-nodejs/assets/2946250/3682c0e5-ca58-4013-8930-c9619cb5ef22)

**Comment by Mantas97** [comment]
Fix released in [1.2.2](https://github.com/mailerlite/mailerlite-nodejs/releases/tag/1.2.2)
