### ISSUE TITLE
subscribers.find(id) returns array of group objects instead of array of group ids as documented

### ISSUE THREAD

**Issue by klcodanr** [mailerlite/mailerlite-nodejs#36]
The documentation for [subscribers.find(id)](https://github.com/mailerlite/mailerlite-nodejs/blob/0e36e792d158c7c325a4515f1edb73a93793208d/src/modules/subscribers/subscribers.module.ts#L50C63-L50C87) indicates that it returns response containing a [SubscriberObject](https://github.com/mailerlite/mailerlite-nodejs/blob/0e36e792d158c7c325a4515f1edb73a93793208d/src/modules/subscribers/subscribers.types.ts#L40). This object indicates that the groups should be returned as string array, however when I use the SDK it _actually_ returns an array of group objects:

![image](https://github.com/mailerlite/mailerlite-nodejs/assets/2946250/d834271b-9176-4a13-90ba-8c77b19e6809)

The API does the same so I assume this is due to the ambiguity in the API docs about the structure of the groups field (esp since on create/update it's described as a list of IDs)

**Comment by Mantas97** [comment]
Fix released in [1.2.2](https://github.com/mailerlite/mailerlite-nodejs/releases/tag/1.2.2)
