### ISSUE TITLE
Resubscribe feature removed from new API

### ISSUE THREAD

**Issue by toppsdown** [mailerlite/mailerlite-nodejs#37]
Mailerlite [V2 API had a flag](https://developers-classic.mailerlite.com/reference/create-a-subscriber) for resubscribing a user. The new version doesn't seem to allow for this.

I've tried setting the status to "active", but get the error: "_This subscriber is unsubscribed and cannot be imported_".

Was this feature removed deliberately? or is there an undocumented way to resubscribe the user?

Thanks,
-Ethan

**Comment by Mantas97** [comment]
Hello Ethan, for questions related to the classic and new API, I'd suggest reaching out to MailerLite [support](https://www.mailerlite.com/help/mailerlite-support-options). They'll be the best to answer this.
