### ISSUE TITLE
export object intefaces

### ISSUE THREAD

**Issue by volodyad** [mailerlite/mailerlite-nodejs#38]
Would be good to use response objects in custom types, e.g 

private async getGroup(groupName: string): Promise<GroupObject> {
}

but no interfaces are exported, so I cannot import GroupObject from '@mailerlite/mailerlite-nodejs'

**Comment by Mantas97** [comment]
MailerLite remains as the default export.
```
import MailerLite from '@mailerlite/mailerlite-nodejs';
```
All types are named exports now
```
import { GroupObject } from '@mailerlite/mailerlite-nodejs';
```
Released in  v`1.2.0`
