### ISSUE TITLE
cannot search group by name

### ISSUE THREAD

**Issue by volodyad** [mailerlite/mailerlite-nodejs#39]
when I try to search group by name 
await this.client.groups.get({
      filter: { name: groupName },
    } as any);

I cannot do this, as filter parameter allows only sent, draft or ready, which is no correct, according to api I should be able to provide group name
interface GetParams$2 {
    filter?: {
        name?: "sent" | "draft" | "ready";
    };
}

**Comment by Mantas97** [comment]
Fixed and released in v`1.2.0`
