### ISSUE TITLE
Incorrect Typings

### ISSUE THREAD

**Issue by olawalejuwonm** [mailerlite/mailerlite-nodejs#42]
The ScheduleCampaignParams contains an incorrect typing. 
`delivery?: "instant" | "scheduled" | "timezone_base` this shows that delivery was made optional, whereas it's required when making the request. See the response below:
![image](https://github.com/mailerlite/mailerlite-nodejs/assets/52759812/e482b4f9-9c02-4c59-bb40-f04866a6824c)

**Comment by olawalejuwonm** [comment]
Looking at it everything was made optional, that implies empty {} can be passed

**Comment by Mantas97** [comment]
Fix released in [1.2.1](https://github.com/mailerlite/mailerlite-nodejs/releases/tag/1.2.1)
