### ISSUE TITLE
Update "Fetch a subscriber" documentation so it shows that either "SUBSCRIBER_ID" or "EMAIL_ADDRESS" can be used as argument

### ISSUE THREAD

**Issue by svenemtell** [mailerlite/mailerlite-nodejs#54]
The "Fetch a subscriber" API states that the argument should be a "SUBSCRIBER_ID", but "EMAIL_ADDRESS" works just as well, just like in the official documentation https://developers.mailerlite.com/docs/subscribers.html#fetch-a-subscriber.

**Comment by Mantas97** [comment]
Docs updated in v[1.3.1](https://github.com/mailerlite/mailerlite-nodejs/releases/tag/1.3.1). Thanks for contributing!
